### ISSUE TITLE
Custom URL Help - ref #347

### ISSUE THREAD

**Issue by bjoern-js** [grafana/django-saml2-auth#351]
The feature from two weeks ago is very nice, however, this does not entirely solve the dynamic URL implementation. 

https://github.com/grafana/django-saml2-auth/pull/348/files

The code in question:
```python
def get_custom_acs_url() -> Optional[str]:
    get_custom_acs_url_hook = dictor(settings.SAML2_AUTH, "TRIGGER.GET_CUSTOM_ASSERTION_URL")
    return run_hook(get_custom_acs_url_hook) if get_custom_acs_url_hook else None
```

The hook never gets the request object passed. In fact, no args or kwargs are passed.

How would one access the mentioned "tenant-1" or "tenant-2" URL parameter?

**Comment by mostafa** [comment]
@henryh9n is a much better person to answer this, yet I suppose you can have them as path parameter, as suggested in [the original issue](https://github.com/grafana/django-saml2-auth/issues/347):

> For example, let's say the base ACS URL is `https://example.com/api/acs`. Since we support multiple tenants, `https://example.com/api/tenant-1/acs` and `https://example.com/api/tenant-2/acs` are also valid ACS URLs, however Django will only find the base one (due to the way we set it up).

**Comment by henryh9n** [comment]
@bjoern-js The reason I made this is that previously the ASC URL was computed as follows:
```python
        acs_url = domain + get_reverse([acs, "acs", "django_saml2_auth:acs"])  # type: ignore
```
this's not always correct, since in some cases (local testing, dynamic routing, etc.) the domain might be different or `get_reverse` reverse function might not work properly.

I agree that it would be even more useful to pass the request/assertion to this function.

We use the trigger in `get_saml_client` function, which has the SAML assertion as an optional parameter (as a string). I'm guessing it would be more useful to pass the Django response here? Or maybe both? Let me know what you think!

In either case, feel free to make a PR to add it, or I can have a look at this the next week.

**Comment by mostafa** [comment]
@bjoern-js Just note that new features and changes must not break backward compatibility. 🙏

**Comment by bjoern-js** [comment]
https://github.com/grafana/django-saml2-auth/compare/main...j0x539:django-saml2-auth:django-saml2-auth/issue351

**Comment by mostafa** [comment]
@bjoern-js Had a quick look and it looks good to me in general. Please send over a PR for review.
